### ISSUE TITLE
Deploying Personal Image on docker hub with `TRY in PWD` button

### ISSUE THREAD

**Issue by liuderchi** [play-with-docker/stacks#21]
I've read your nice article https://medium.com/@marcosnils/showcasing-your-applications-with-docker-in-a-single-click-9e9fa2908c51 and played with the awesome query string `stack=/foo/bar` feature 👍 .

💡 Now I'd like to deploy some side project image on PWD with `TRY in PWD`.

❓ Would it possible to do it with `stack=/foo/bar` feature without putting yaml on this repo?

**Comment by marcosnils** [comment]
Yes, you can host the yaml anywhere you like. In the stack parameter you can enter any url

**Comment by liuderchi** [comment]
@marcosnils thanks for your answer.

I found __the `stack.yml` name should be fixed. (no instances shown up otherwise)__

However, I've seen several query string cases like:

- `?stack=https://example.com/foo/bar/docker-compose.yml&stack_name=hackmd`

❓ _So how does query string `stack_name` effect the result?
How to set it properly?_

( Currently I found it supports 3 query strings: [`stack`, `stack_name`, `image_name`](https://github.com/play-with-docker/play-with-docker/blob/786933468e1480d716e8324e33af1ef92c67e64d/www/default/landing.html#L49-L51
), and 
the `stack_name` set to `"pwd"` if not specified)

**Comment by marcosnils** [comment]
> So how does query string stack_name effect the result?

This is the `stack` name that gets assigned when doing `docker stack deploy` of your yml file.



> How to set it properly?

There's no really a proper way to set it up, we made it configurable as some projects rely on a specific task name to work.

**Comment by NeverBehave** [comment]
Is it possible to also pass in `.env` file for the `stack.yml`?

https://docs.docker.com/compose/environment-variables/#the-env-file

**Comment by marcosnils** [comment]
Nope

**Comment by marcbria** [comment]
Any workaround for stacks that require an env file?
If not, passing an env as a second querystring param sounds like a nice addition.
