### ISSUE TITLE
Wrong redirection for UCP stack.

### ISSUE THREAD

**Issue by arush-sal** [play-with-docker/stacks#6]
Issue: The redirection link for UCP should be [http://labs.play-with-docker.com/?stack=/docker/ucp/stack.yml](http://labs.play-with-docker.com/?stack=/docker/ucp/stack.yml) instead it is being redirected as [http://labs.play-with-docker.com/?stack=/docker/ucp/stack.yml/stack.yml](http://labs.play-with-docker.com/?stack=/docker/ucp/stack.yml/stack.yml).

Steps to reproduce: Got to hub.docker.com/r/docker/ucp, click on "Try in PWD" and then click on "try" on right-hand side of the pop-up.

**Comment by marcosnils** [comment]
@arush-sal thx for reporting. Should be fixed now.

**Comment by arush-sal** [comment]
Yup, it took some time to get started but it definitely seems fixed :)

p.s: that was quick as flash(:zap:) ;)
